version: "3.8"

networks:
    nginx_network:
    internal:

services:
    market-app:
        image: adhocore/phpfpm:8.1
        container_name: market-app
        working_dir: /app
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - '.:/app'
            - './docker/php/overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        links:
            - market-database
        depends_on:
            - market-database
    market-nginx:
        image: nginx:alpine
        container_name: market-nginx
        restart: always
        working_dir: /app
        networks:
            - internal
            - nginx_network
        ports:
            - "9008:80"
        volumes:
            - .:/app
            - ./docker/nginx/my.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - market-app
    market-database:
        image: postgres:14.2-alpine
        container_name: market-database
        working_dir: /app
        networks:
            - internal
            - nginx_network
        environment:
            POSTGRES_DB: market_db
            POSTGRES_USER: market_user
            POSTGRES_PASSWORD: market_password
        volumes:
            - .:/app
        ports:
            - '5432:5432'
    market-composer:
        image: composer:latest
        container_name: market-composer
        working_dir: /app
        command: update --ignore-platform-reqs
        volumes:
            - .:/app
        restart: on-failure
        depends_on:
            - market-app
volumes:
  market-database:
    driver: local
